# The application's global config file...

# Display Device
DISP_WIDTH: 3840
DISP_HEIGHT: 2160

# EEG Device
EEG_BOARD_ID: 0
EEG_BOARD_SERIAL_PORT: /dev/ttyUSB0
EYETRACKER_SAMPLE_HZ: 250  # 4ms per sample
EEG_SZ_DATA_BUFF: 45000
EEG_BCI_HUB_PATH: /opt/app/dependencies/OpenBCI_Hub/OpenBCIHub

# Eyetracker Device
EYETRACKER_SAMPLE_HZ: 90
EYETRACKER_BUFF_SZ: 45000
EYETRACKER_MARK_INTERVAL: 8
EYETRACKER_EXTERN_LIB_PATH: /opt/app/src/lib/so/eyetracker_gaze.so
EYETRACKER_PREP_SCRIPT_PATH: /opt/app/src/lib/sh/prep_eyetracker_gaze.sh

# Event Logging
EVENTLOG_ROOTDIR: /opt/app/data/event_logs
EVENTLOG_EEG_SUBDIR: eeg
EVENTLOG_GAZE_SUBDIR: gaze
EVENTLOG_KEYB_SUBDIR: keyboard
EVENTLOG_MOUSE_SUBDIR: mouse
EVENTLOG_NOTEFILE_FNAME: 'NOTES.md'
EVENTLOG_GAZE_TIME_CONVERT_IPLIER: .000001
EVENTLOG_EEG_COLS: ['timestamp',
                    'eeg_0',
                    'eeg_1',
                    'eeg_2',
                    'eeg_3',
                    'eeg_4',
                    'eeg_5',
                    'eeg_6',
                    'eeg_7']
EVENTLOG_GAZE_COLS: ['timestamp_us', x, 'y']
EVENTLOG_KEYB_COLS: ['timestamp',       
                     'key_code',      # ASCII
                     'event_code']    # 1 = key_down, 0 = key_up
EVENTLOG_MOUSE_COLS: ['timestamp',      
                      'btn_code',     # 1 = L, 2 = M, 3 = R, 4 = scroll, 0 = unk
                      'event_code']   # 1 = click OR scroll_up, 0 = scroll_down

EVENTLOG_WRITEBACK_SECONDS: 10
EVENTLOG_WRITEAFTER_SECONDS: 10
