# The application's global config file...

# Display Device
DISP_WIDTH_MM: 698.5
DISP_HEIGHT_MM: 393.7
DISP_WIDTH_PX: 3840
DISP_HEIGHT_PX: 2160

# On-screen Keyboard/HUD
HUD_DISP_TITLE: 'AEye TypeR'
HUD_DISP_WIDTH_PX: 1222
HUD_DISP_HEIGHT_PX: 253
HUD_POSGUIDE_WIDTH_PX: 160
HUD_DISP_COORD_DIVISOR_X: 1.5
HUD_DISP_COORD_DIVISOR_Y: 1
HUD_BTN_WIDTH: 2
HUD_KEYB_JSON: 'lib/json/keyboard_us.json'

# Eyetracker Device
EYETRACKER_SAMPLE_HZ: 90
EYETRACKER_BUFF_SZ: 60
EYETRACKER_MARK_INTERVAL: 10
EYETRACKER_SMOOTH_OVER: 4
EYETRACKER_EXTERN_LIB_PATH: /opt/app/src/lib/so/eyetracker_gaze.so
EYETRACKER_PREP_SCRIPT_PATH: /opt/app/src/lib/sh/prep_eyetracker_gaze.sh

# Event Logging
EVENTLOG_RAW_ROOTDIR: /opt/app/data/event_logs/raw      # Raw log data (.csv)
EVENTLOG_SAMPLED_ROOTDIR: /opt/app/data/event_logs/sampled  # Parsed log data (.sqlite)
EVENTLOG_HUD_SUBDIR: hud                                # Subdir in raw and sampled dirs
EVENTLOG_GAZE_SUBDIR: gaze                              # Subdir in raw and sampled dirs
EVENTLOG_KEYB_SUBDIR: keyboard                          # Subdir in raw and sampled dirs
EVENTLOG_MOUSE_SUBDIR: mouse                            # Subdir in raw and sampled dirs
EVENTLOG_NOTEFILE_FNAME: 'NOTES.md'
EVENTLOG_GAZE_TIME_CONVERT_IPLIER: .000001

EVENTLOG_KEYB_COLS: ['timestamp',       
                     'key_code',      # ASCII
                     'event_code']    # 1 = key_down, 0 = key_up
EVENTLOG_MOUSE_COLS: ['timestamp',      
                      'btn_code',     # 1 = L, 2 = M, 3 = R, 4 = scroll, 0 = unk
                      'event_code',   # 1 = click OR scroll_up, 0 = scroll_down
                      'x',
                      'y']
EVENTLOG_WRITEBACK_SECONDS: 7
EVENTLOG_WRITEAFTER_SECONDS: 7

# Data Parsing
