# The application's global config file...

# Display Device
DISP_WIDTH: 3840
DISP_HEIGHT: 2160

# EEG Device
EEG_BOARD_ID: 0
EEG_BOARD_SERIAL_PORT: /dev/ttyUSB0
EEG_SZ_DATA_BUFF: 450000
EEG_BCI_HUB_PATH: /opt/app/dependencies/OpenBCI_Hub/OpenBCIHub

# Eyetracker Device
EYETRACKER_BUFF_SZ: 450000
EYETRACKER_MARK_INTERVAL: 8
EYETRACKER_EXTERN_LIB_PATH: /opt/app/src/lib/so/eyetracker_gaze.so
EYETRACKER_PREP_SCRIPT_PATH: /opt/app/src/lib/sh/prep_eyetracker_gaze.sh

# Event Logging
EVENTLOG_ROOTDIR: /opt/app/data/event_logs
EVENTLOG_CSV_SUBDIR: raw_csv
EVENTLOG_EEG_SUBDIR: eeg
EVENTLOG_GAZE_SUBDIR: gaze
EVENTLOG_KEYS_SUBDIR: keyboard
EVENTLOG_MOUSE_SUBDIR: mouse
EVENTLOG_NOTEFILE_FNAME: 'NOTES.md'

EVENTLOG_EEG_WRITEBACK_SECONDS: 20
EVENTLOG_EEG_WRITEAFTER_SECONDS: 20

EVENTLOG_SIGNAL_EVENT: True
EVENTLOG_SIGNAL_STOP: False