# The application's global config file...

# Display Device - sm
DISP_WIDTH_MM: 523.875
DISP_HEIGHT_MM: 295.275
DISP_WIDTH_PX: 1920
DISP_HEIGHT_PX: 1080

# Display Device - lg
# DISP_WIDTH_MM: 698.5
# DISP_HEIGHT_MM: 393.7
# DISP_WIDTH_PX: 3840
# DISP_HEIGHT_PX: 2160

# On-screen Keyboard/HUD
HUD_DISP_TITLE: 'AEye TypeR'
HUD_DISP_WIDTH_PX: 1222
HUD_DISP_HEIGHT_PX: 253
HUD_POSGUIDE_WIDTH_PX: 160
HUD_DISP_COORD_DIVISOR_X: 1.5
HUD_DISP_COORD_DIVISOR_Y: 1
HUD_BTN_WIDTH: 2
HUD_KEYB_JSON: 'lib/json/keyboard_us.json'

# Eyetracker Device
EYETRACKER_SAMPLE_HZ: 90
EYETRACKER_BUFF_SZ: 45000
EYETRACKER_MARK_INTERVAL: 5
EYETRACKER_SMOOTH_OVER: 15
EYETRACKER_EXTERN_LIB_PATH: lib/so/eyetracker_gaze.so
EYETRACKER_PREP_SCRIPT_PATH: lib/sh/prep_eyetracker_gaze.sh
EYETRACKER_WRITEBACK_SECONDS: 7
EYETRACKER_WRITEAFTER_SECONDS: 7

# Event Logging
EVENTLOG_RAW_ROOTDIR: /opt/app/data/logs      # Raw log data directory

# Data processing
# GAZE_TIME_CONVERT_IPLIER: .000001
GAZE_TIME_CONVERT_IPLIER: .00001
MOUSE_TIME_CONVERT_IPLIER: 10
