
# File / Directory Paths
APP_DATA_DIR: /opt/app/data
APP_KEY_EVENTS_DB_PATH: /opt/app/data/key_events.sql

# Device IDs
DEVICE_ID_DISPLAY: ":0"
DEVICE_ID_KEYBOARD: "12"
DEVICE_ID_MOUSE: "11"
DEVICE_ID_EEG_BOARD: 0
DEVICE_ID_EEG: /dev/ttyUSB0