# The application's global config file...


# EEG Device
EEG_BOARD_ID: 0
EEG_BOARD_SERIAL_PORT: /dev/ttyUSB0
EEG_SZ_DATA_BUFF: 450000
EEG_BCI_HUB_PATH: /opt/app/dependencies/OpenBCI_Hub/OpenBCIHub

# Event Logging
EVENTLOG_ROOTDIR: /opt/app/data/event_logs
EVENTLOG_CSV_SUBDIR: raw_csv
EVENTLOG_EEG_SUBDIR: eeg
EVENTLOG_KEYS_SUBDIR: keyboard
EVENTLOG_MOUSE_SUBDIR: mouse
EVENTLOG_NOTEFILE_FNAME: 'NOTES.md'

EVENTLOG_EEG_WRITEBACK_SECONDS: 20
EVENTLOG_EEG_WRITEAFTER_SECONDS: 20

EVENTLOG_SIGNAL_EVENT: True
EVENTLOG_SIGNAL_STOP: False